name: Detect Picta IPA Update

on:
  push:
    paths:
      - "ipa/Picta*.ipa" # 监听 ipa 文件夹下的以 Picta 开头、.ipa 结尾的文件上传或修改

jobs:
  generate_update_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version and create gengxin.txt
      run: |
        # 检查是否存在 ipa 文件夹
        if [ ! -d "ipa" ]; then
          echo "ipa folder does not exist! Exiting workflow..."
          exit 1
        fi

        # 进入 ipa 文件夹
        cd ipa

        # 找到最新的 Picta*.ipa 文件
        latest_file=$(ls Picta*.ipa | tail -n 1)

        # 确保找到文件
        if [ -z "$latest_file" ]; then
          echo "No Picta*.ipa file found! Exiting workflow..."
          exit 1
        fi

        # 提取版本号（即去除 Picta 和 .ipa 的部分）
        version=$(echo "$latest_file" | sed -E 's/Picta(.*)\.ipa/\1/')

        # 打印日志以便调试
        echo "Detected file: $latest_file"
        echo "Extracted version: $version"

        # 生成 gengxin.txt 文件，内容为版本号
        echo "【$version】" > gengxin.txt

    - name: Commit and push changes
      run: |
        # 检查是否有修改
        if [ -f "ipa/gengxin.txt" ]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 添加 gengxin.txt 到 Git
          git add ipa/gengxin.txt

          # 提交更改
          git commit -m "Auto-generate gengxin.txt for $latest_file"

          # 推送到仓库
          git push
        else
          echo "No gengxin.txt generated, skipping commit."
        fi
